name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Flake8 linter
      run: flake8 hexlet_code tests  # Проверяем код в hexlet_code и tests

    - name: Run tests with pytest
      run: pytest --cov=hexlet_code --cov-report xml  # Запускаем тесты и генерируем отчет о покрытии

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Optional: upload to a specific Codecov project
        fail_ci_if_error: true # Optional: always fail CI if the Codecov uploader errors

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: build  # Зависимость от успешного завершения job build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install SonarScanner
        run: |
          wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.2.0.5079-linux-x64.zip
          unzip -q sonar-scanner-cli-7.2.0.5079-linux-x64.zip
          echo "$PWD/sonar-scanner-7.2.0.5079-linux-x64/bin" >> $GITHUB_PATH

      - name: Run SonarScanner
        run: |
          sonar-scanner --version
          sonar-scanner \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.branch.name=${GITHUB_REF##*/} \
            -Dsonar.branch.target=${GITHUB_BASE_REF}
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}