name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    name: Run tests and linting with uv
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Install dependencies
      run: uv sync --dev --frozen
    
    - name: Run linter (Ruff)
      run: uv run ruff check .
    
    - name: Run type checker (optional)
      run: uv run ruff check --select I .  # Проверка импортов
      continue-on-error: true  # Опциональный шаг
    
    - name: Run tests with coverage
      run: uv run pytest --cov=hexlet_code --cov-report=xml -v
    
    - name: Upload coverage to SonarQube
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: github.event_name == 'pull_request'
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}  # Если используете Codecov
      if: github.event_name == 'push'