name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  UV_PROJECT_ENVIRONMENT: .venv
  UV_PYTHON: "3.12"

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Install Python
      run: uv python install ${{ env.UV_PYTHON }}
    
    - name: Sync dependencies
      run: uv sync --dev --frozen
    
    - name: Check code formatting
      run: uv run ruff format --check .
    
    - name: Check code quality
      run: uv run ruff check .
    
    - name: Install the package in development mode
      run: uv pip install -e .
    
    - name: Run tests with coverage
      run: |
        uv run pytest --cov=gendiff --cov-report=xml --cov-report=html --junitxml=test-results.xml -v
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Generate coverage report
      run: uv run coverage report
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          coverage.xml
          htmlcov/
        retention-days: 30

  sonar-scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Download coverage reports
      uses: actions/download-artifact@v4
      with:
        name: coverage-reports
    
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=IDarhanI_python-project-50
          -Dsonar.organization=idarhani
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.python.xunit.reportPath=test-results.xml
          -Dsonar.sources=gendiff
          -Dsonar.tests=tests
          -Dsonar.coverage.exclusions=tests/*,**/__init__.py