name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  UV_PROJECT_ENVIRONMENT: .venv
  UV_PYTHON: "3.12"

jobs:
  test-and-sonar:
    name: Test & SonarQube
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Install Python
      run: uv python install ${{ env.UV_PYTHON }}
    
    - name: Sync dependencies
      run: uv sync --dev --frozen
    
    - name: Run linter
      run: |
        uv run ruff check .
        uv run ruff format --check .
    
    - name: Install the package in development mode
      run: uv pip install -e .
    
    - name: Run tests with coverage
      run: |
        uv run pytest --cov=gendiff --cov-report=xml --cov-report=html --junitxml=test-results.xml -v
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Debug coverage info
      run: |
        uv run coverage report
        echo "Current directory: $(pwd)"
        echo "Python path: $PYTHONPATH"
    
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=IDarhanI_python-project-50
          -Dsonar.organization=idarhani
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.python.xunit.reportPath=test-results.xml
          -Dsonar.sources=gendiff
          -Dsonar.tests=tests
          -Dsonar.coverage.exclusions=tests/*,**/__init__.py
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          coverage.xml
          htmlcov/
          test-results.xml
        retention-days: 30
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.xml
        retention-days: 30